In [1]:
import pandas as pd
from pathlib import Path
import glob
results_folder = "../Data/raw/fastf1/results"
laps_folder = "../Data/raw/fastf1/laps"
weather_folder = "../Data/raw/fastf1/weather"

In [2]:
result_files = glob.glob(f"{results_folder}/*.csv")

results_df = pd.concat(
    [pd.read_csv(file) for file in result_files],
    ignore_index=True
)

print(f"Loaded {len(result_files)} results files")
print(results_df.shape)

results_df.head()

Loaded 140 results files
(2798, 22)

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
0,33,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,1E41FF,red_bull,Max,Verstappen,Max Verstappen,...,1.0,1,4.0,NaN,NaN,NaN,0 days 01:19:41.993000,Finished,25.0,52.0
1,44,L HAMILTON,HAM,hamilton,Mercedes,00D2BE,mercedes,Lewis,Hamilton,Lewis Hamilton,...,2.0,2,2.0,NaN,NaN,NaN,0 days 00:00:11.326000,Finished,19.0,52.0
2,77,V BOTTAS,BOT,bottas,Mercedes,00D2BE,mercedes,Valtteri,Bottas,Valtteri Bottas,...,3.0,3,1.0,NaN,NaN,NaN,0 days 00:00:19.231000,Finished,15.0,52.0
3,16,C LECLERC,LEC,leclerc,Ferrari,DC0000,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,4,8.0,NaN,NaN,NaN,0 days 00:00:29.289000,Finished,12.0,52.0
4,23,A ALBON,ALB,albon,Red Bull Racing,1E41FF,red_bull,Alexander,Albon,Alexander Albon,...,5.0,5,9.0,NaN,NaN,NaN,0 days 00:00:39.146000,Finished,10.0,52.0

In [3]:
lap_files = glob.glob(f"{laps_folder}/*.csv")

laps_df = pd.concat(
    [pd.read_csv(file) for file in lap_files],
    ignore_index=True
)

print(f"Loaded {len(lap_files)} lap files")
print(laps_df.shape)

laps_df.head()

Loaded 139 lap files
(151985, 31)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:34:52.538000,VER,33,0 days 00:01:35.298000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:37.475000,...,False,Red Bull Racing,0 days 00:33:17.072000,2020-08-09 13:13:17.118,12.0,3.0,False,NaN,False,False
1,0 days 00:36:24.506000,VER,33,0 days 00:01:31.968000,2.0,1.0,NaN,NaN,0 days 00:00:29.202000,0 days 00:00:37.476000,...,False,Red Bull Racing,0 days 00:34:52.538000,2020-08-09 13:14:52.584,1.0,3.0,False,NaN,False,True
2,0 days 00:37:56.478000,VER,33,0 days 00:01:31.972000,3.0,1.0,NaN,NaN,0 days 00:00:29.072000,0 days 00:00:37.527000,...,False,Red Bull Racing,0 days 00:36:24.506000,2020-08-09 13:16:24.552,1.0,3.0,False,NaN,False,True
3,0 days 00:39:28.603000,VER,33,0 days 00:01:32.125000,4.0,1.0,NaN,NaN,0 days 00:00:29.030000,0 days 00:00:37.655000,...,False,Red Bull Racing,0 days 00:37:56.478000,2020-08-09 13:17:56.524,1.0,3.0,False,NaN,False,True
4,0 days 00:41:00.854000,VER,33,0 days 00:01:32.251000,5.0,1.0,NaN,NaN,0 days 00:00:29.169000,0 days 00:00:37.646000,...,False,Red Bull Racing,0 days 00:39:28.603000,2020-08-09 13:19:28.649,1.0,3.0,False,NaN,False,True

In [4]:
weather_files = glob.glob(f"{weather_folder}/*.csv")

weather_df = pd.concat(
    [pd.read_csv(file) for file in weather_files],
    ignore_index=True
)

print(f"Loaded {len(weather_files)} weather files")
print(weather_df.shape)

weather_df.head()

Loaded 139 weather files
(21982, 8)

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:29.925000,23.7,63.0,1001.4,False,41.5,5,2.3
1,0 days 00:01:29.929000,23.8,62.8,1001.4,False,41.3,7,2.8
2,0 days 00:02:29.943000,23.7,62.4,1001.4,False,41.1,15,1.3
3,0 days 00:03:29.952000,23.6,62.8,1001.4,False,41.0,18,2.2
4,0 days 00:04:29.944000,23.9,61.9,1001.4,False,41.3,20,2.8

In [5]:
results_df.info()
results_df.isnull().sum()
results_df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2798 entries, 0 to 2797
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        2798 non-null   int64
 1   BroadcastName       2795 non-null   object
 2   Abbreviation        2798 non-null   object
 3   DriverId            2798 non-null   object
 4   TeamName            2798 non-null   object
 5   TeamColor           2795 non-null   object
 6   TeamId              2798 non-null   object
 7   FirstName           2798 non-null   object
 8   LastName            2798 non-null   object
 9   FullName            2798 non-null   object
 10  HeadshotUrl         2708 non-null   object
 11  CountryCode         1457 non-null   object
 12  Position            2795 non-null   float64
 13  ClassifiedPosition  2798 non-null   object
 14  GridPosition        2795 non-null   float64
 15  Q1                  0 non-null      float64
 16  Q2                  0 non-null      float64
 17  Q3                  0 non-null      float64
 18  Time                2040 non-null   object
 19  Status              2798 non-null   object
 20  Points              2798 non-null   float64
 21  Laps                2798 non-null   float64
dtypes: float64(7), int64(1), object(14)
memory usage: 481.0+ KB

np.int64(183)

In [6]:
laps_df.info()
laps_df.isnull().sum()
laps_df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151985 entries, 0 to 151984
Data columns (total 31 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Time                151985 non-null  object
 1   Driver              151985 non-null  object
 2   DriverNumber        151985 non-null  int64
 3   LapTime             149393 non-null  object
 4   LapNumber           151985 non-null  float64
 5   Stint               151631 non-null  float64
 6   PitOutTime          5148 non-null    object
 7   PitInTime           5205 non-null    object
 8   Sector1Time         148680 non-null  object
 9   Sector2Time         151666 non-null  object
 10  Sector3Time         151496 non-null  object
 11  Sector1SessionTime  148299 non-null  object
 12  Sector2SessionTime  151666 non-null  object
 13  Sector3SessionTime  151496 non-null  object
 14  SpeedI1             151742 non-null  float64
 15  SpeedI2             150855 non-null  float64
 16  SpeedFL             146540 non-null  float64
 17  SpeedST             151665 non-null  float64
 18  IsPersonalBest      151801 non-null  object
 19  Compound            151205 non-null  object
 20  TyreLife            150927 non-null  float64
 21  FreshTyre           151985 non-null  bool
 22  Team                151985 non-null  object
 23  LapStartTime        151985 non-null  object
 24  LapStartDate        151985 non-null  object
 25  TrackStatus         151962 non-null  float64
 26  Position            151744 non-null  float64
 27  Deleted             151985 non-null  bool
 28  DeletedReason       1816 non-null    object
 29  FastF1Generated     151985 non-null  bool
 30  IsAccurate          151985 non-null  bool
dtypes: bool(4), float64(9), int64(1), object(17)
memory usage: 31.9+ MB

np.int64(9527)

In [7]:
weather_df.info()
weather_df.isnull().sum()
weather_df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21982 entries, 0 to 21981
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Time           21982 non-null  object
 1   AirTemp        21982 non-null  float64
 2   Humidity       21982 non-null  float64
 3   Pressure       21982 non-null  float64
 4   Rainfall       21982 non-null  bool
 5   TrackTemp      21982 non-null  float64
 6   WindDirection  21982 non-null  int64
 7   WindSpeed      21982 non-null  float64
dtypes: bool(1), float64(5), int64(1), object(1)
memory usage: 1.2+ MB

np.int64(1406)

# Inspect Data

In [8]:
results_df.info()
results_df.describe(include="all")
results_df.isnull().sum()
results_df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2798 entries, 0 to 2797
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        2798 non-null   int64
 1   BroadcastName       2795 non-null   object
 2   Abbreviation        2798 non-null   object
 3   DriverId            2798 non-null   object
 4   TeamName            2798 non-null   object
 5   TeamColor           2795 non-null   object
 6   TeamId              2798 non-null   object
 7   FirstName           2798 non-null   object
 8   LastName            2798 non-null   object
 9   FullName            2798 non-null   object
 10  HeadshotUrl         2708 non-null   object
 11  CountryCode         1457 non-null   object
 12  Position            2795 non-null   float64
 13  ClassifiedPosition  2798 non-null   object
 14  GridPosition        2795 non-null   float64
 15  Q1                  0 non-null      float64
 16  Q2                  0 non-null      float64
 17  Q3                  0 non-null      float64
 18  Time                2040 non-null   object
 19  Status              2798 non-null   object
 20  Points              2798 non-null   float64
 21  Laps                2798 non-null   float64
dtypes: float64(7), int64(1), object(14)
memory usage: 481.0+ KB

np.int64(183)

In [9]:
laps_df.info()
laps_df.describe(include="all")
laps_df.isnull().sum()
laps_df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151985 entries, 0 to 151984
Data columns (total 31 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Time                151985 non-null  object
 1   Driver              151985 non-null  object
 2   DriverNumber        151985 non-null  int64
 3   LapTime             149393 non-null  object
 4   LapNumber           151985 non-null  float64
 5   Stint               151631 non-null  float64
 6   PitOutTime          5148 non-null    object
 7   PitInTime           5205 non-null    object
 8   Sector1Time         148680 non-null  object
 9   Sector2Time         151666 non-null  object
 10  Sector3Time         151496 non-null  object
 11  Sector1SessionTime  148299 non-null  object
 12  Sector2SessionTime  151666 non-null  object
 13  Sector3SessionTime  151496 non-null  object
 14  SpeedI1             151742 non-null  float64
 15  SpeedI2             150855 non-null  float64
 16  SpeedFL             146540 non-null  float64
 17  SpeedST             151665 non-null  float64
 18  IsPersonalBest      151801 non-null  object
 19  Compound            151205 non-null  object
 20  TyreLife            150927 non-null  float64
 21  FreshTyre           151985 non-null  bool
 22  Team                151985 non-null  object
 23  LapStartTime        151985 non-null  object
 24  LapStartDate        151985 non-null  object
 25  TrackStatus         151962 non-null  float64
 26  Position            151744 non-null  float64
 27  Deleted             151985 non-null  bool
 28  DeletedReason       1816 non-null    object
 29  FastF1Generated     151985 non-null  bool
 30  IsAccurate          151985 non-null  bool
dtypes: bool(4), float64(9), int64(1), object(17)
memory usage: 31.9+ MB

np.int64(9527)

In [10]:
weather_df.info()
weather_df.describe(include="all")
weather_df.isnull().sum()
weather_df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21982 entries, 0 to 21981
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Time           21982 non-null  object
 1   AirTemp        21982 non-null  float64
 2   Humidity       21982 non-null  float64
 3   Pressure       21982 non-null  float64
 4   Rainfall       21982 non-null  bool
 5   TrackTemp      21982 non-null  float64
 6   WindDirection  21982 non-null  int64
 7   WindSpeed      21982 non-null  float64
dtypes: bool(1), float64(5), int64(1), object(1)
memory usage: 1.2+ MB

np.int64(1406)

In [11]:
results_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2798 entries, 0 to 2797
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        2798 non-null   int64
 1   BroadcastName       2795 non-null   object
 2   Abbreviation        2798 non-null   object
 3   DriverId            2798 non-null   object
 4   TeamName            2798 non-null   object
 5   TeamColor           2795 non-null   object
 6   TeamId              2798 non-null   object
 7   FirstName           2798 non-null   object
 8   LastName            2798 non-null   object
 9   FullName            2798 non-null   object
 10  HeadshotUrl         2708 non-null   object
 11  CountryCode         1457 non-null   object
 12  Position            2795 non-null   float64
 13  ClassifiedPosition  2798 non-null   object
 14  GridPosition        2795 non-null   float64
 15  Q1                  0 non-null      float64
 16  Q2                  0 non-null      float64
 17  Q3                  0 non-null      float64
 18  Time                2040 non-null   object
 19  Status              2798 non-null   object
 20  Points              2798 non-null   float64
 21  Laps                2798 non-null   float64
dtypes: float64(7), int64(1), object(14)
memory usage: 481.0+ KB

In [12]:
results_df.isnull().sum()

DriverNumber             0
BroadcastName            3
Abbreviation             0
DriverId                 0
TeamName                 0
TeamColor                3
TeamId                   0
FirstName                0
LastName                 0
FullName                 0
HeadshotUrl             90
CountryCode           1341
Position                 3
ClassifiedPosition       0
GridPosition             3
Q1                    2798
Q2                    2798
Q3                    2798
Time                   758
Status                   0
Points                   0
Laps                     0
dtype: int64

In [13]:
results_df.duplicated().sum()

np.int64(183)

In [14]:
results_df[results_df.duplicated()].head(20)

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
220,77,V BOTTAS,BOT,bottas,Mercedes,00D2BE,mercedes,Valtteri,Bottas,Valtteri Bottas,...,1.0,1,1.0,NaN,NaN,NaN,0 days 01:30:55.739000,Finished,25.0,71.0
221,16,C LECLERC,LEC,leclerc,Ferrari,DC0000,ferrari,Charles,Leclerc,Charles Leclerc,...,2.0,2,7.0,NaN,NaN,NaN,0 days 00:00:02.700000,Finished,18.0,71.0
222,4,L NORRIS,NOR,norris,McLaren,FF8700,mclaren,Lando,Norris,Lando Norris,...,3.0,3,3.0,NaN,NaN,NaN,0 days 00:00:05.491000,Finished,16.0,71.0
223,44,L HAMILTON,HAM,hamilton,Mercedes,00D2BE,mercedes,Lewis,Hamilton,Lewis Hamilton,...,4.0,4,5.0,NaN,NaN,NaN,0 days 00:00:05.689000,Finished,12.0,71.0
224,55,C SAINZ,SAI,sainz,McLaren,FF8700,mclaren,Carlos,Sainz,Carlos Sainz,...,5.0,5,8.0,NaN,NaN,NaN,0 days 00:00:08.903000,Finished,10.0,71.0
225,11,S PEREZ,PER,perez,Racing Point,F596C8,racing_point,Sergio,Perez,Sergio Perez,...,6.0,6,6.0,NaN,NaN,NaN,0 days 00:00:15.092000,Finished,8.0,71.0
226,10,P GASLY,GAS,gasly,AlphaTauri,ffffff,alphatauri,Pierre,Gasly,Pierre Gasly,...,7.0,7,12.0,NaN,NaN,NaN,0 days 00:00:16.682000,Finished,6.0,71.0
227,31,E OCON,OCO,ocon,Renault,FFF500,renault,Esteban,Ocon,Esteban Ocon,...,8.0,8,14.0,NaN,NaN,NaN,0 days 00:00:17.456000,Finished,4.0,71.0
228,99,A GIOVINAZZI,GIO,giovinazzi,Alfa Romeo Racing,9B0000,alfa,Antonio,Giovinazzi,Antonio Giovinazzi,...,9.0,9,18.0,NaN,NaN,NaN,0 days 00:00:21.146000,Finished,2.0,71.0
229,5,S VETTEL,VET,vettel,Ferrari,DC0000,ferrari,Sebastian,Vettel,Sebastian Vettel,...,10.0,10,11.0,NaN,NaN,NaN,0 days 00:00:24.545000,Finished,1.0,71.0
230,6,N LATIFI,LAT,latifi,Williams,0082fa,williams,Nicholas,Latifi,Nicholas Latifi,...,11.0,11,20.0,NaN,NaN,NaN,0 days 00:00:31.650000,Finished,0.0,71.0
231,26,D KVYAT,KVY,kvyat,AlphaTauri,ffffff,alphatauri,Daniil,Kvyat,Daniil Kvyat,...,12.0,12,13.0,NaN,NaN,NaN,NaN,Suspension,0.0,69.0
232,23,A ALBON,ALB,albon,Red Bull Racing,1E41FF,red_bull,Alexander,Albon,Alexander Albon,...,13.0,13,4.0,NaN,NaN,NaN,NaN,Electronics,0.0,67.0
233,7,K RAIKKONEN,RAI,raikkonen,Alfa Romeo Racing,9B0000,alfa,Kimi,Räikkönen,Kimi Räikkönen,...,14.0,R,19.0,NaN,NaN,NaN,NaN,Wheel,0.0,53.0
234,63,G RUSSELL,RUS,russell,Williams,0082fa,williams,George,Russell,George Russell,...,15.0,R,17.0,NaN,NaN,NaN,NaN,Fuel pressure,0.0,49.0
235,8,R GROSJEAN,GRO,grosjean,Haas F1 Team,787878,haas,Romain,Grosjean,Romain Grosjean,...,16.0,R,15.0,NaN,NaN,NaN,NaN,Brakes,0.0,49.0
236,20,K MAGNUSSEN,MAG,kevin_magnussen,Haas F1 Team,787878,haas,Kevin,Magnussen,Kevin Magnussen,...,17.0,R,16.0,NaN,NaN,NaN,NaN,Brakes,0.0,24.0
237,18,L STROLL,STR,stroll,Racing Point,F596C8,racing_point,Lance,Stroll,Lance Stroll,...,18.0,R,9.0,NaN,NaN,NaN,NaN,Engine,0.0,20.0
238,3,D RICCIARDO,RIC,ricciardo,Renault,FFF500,renault,Daniel,Ricciardo,Daniel Ricciardo,...,19.0,R,10.0,NaN,NaN,NaN,NaN,Overheating,0.0,17.0
239,33,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,1E41FF,red_bull,Max,Verstappen,Max Verstappen,...,20.0,R,2.0,NaN,NaN,NaN,NaN,Electronics,0.0,11.0

In [15]:
results_df = results_df.drop_duplicates()

print(results_df.shape)

(2615, 22)

In [16]:
results_df.drop(columns=["Q1", "Q2", "Q3"], inplace=True)

In [17]:
results_df.drop(columns=["CountryCode"], inplace=True)

In [18]:
results_df.drop(columns=["HeadshotUrl"], inplace=True)

In [20]:
print(results_df.columns.tolist())

['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName', 'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName', 'Position', 'ClassifiedPosition', 'GridPosition', 'Time', 'Status', 'Points', 'Laps']

In [21]:
results_df.duplicated().sum()

np.int64(0)

In [22]:
results_df.to_csv(
    "../Data/processed/clean_results.csv",
    index=False
)

print("✅ Clean Results dataset saved.")

✅ Clean Results dataset saved.

In [23]:
laps_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151985 entries, 0 to 151984
Data columns (total 31 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Time                151985 non-null  object
 1   Driver              151985 non-null  object
 2   DriverNumber        151985 non-null  int64
 3   LapTime             149393 non-null  object
 4   LapNumber           151985 non-null  float64
 5   Stint               151631 non-null  float64
 6   PitOutTime          5148 non-null    object
 7   PitInTime           5205 non-null    object
 8   Sector1Time         148680 non-null  object
 9   Sector2Time         151666 non-null  object
 10  Sector3Time         151496 non-null  object
 11  Sector1SessionTime  148299 non-null  object
 12  Sector2SessionTime  151666 non-null  object
 13  Sector3SessionTime  151496 non-null  object
 14  SpeedI1             151742 non-null  float64
 15  SpeedI2             150855 non-null  float64
 16  SpeedFL             146540 non-null  float64
 17  SpeedST             151665 non-null  float64
 18  IsPersonalBest      151801 non-null  object
 19  Compound            151205 non-null  object
 20  TyreLife            150927 non-null  float64
 21  FreshTyre           151985 non-null  bool
 22  Team                151985 non-null  object
 23  LapStartTime        151985 non-null  object
 24  LapStartDate        151985 non-null  object
 25  TrackStatus         151962 non-null  float64
 26  Position            151744 non-null  float64
 27  Deleted             151985 non-null  bool
 28  DeletedReason       1816 non-null    object
 29  FastF1Generated     151985 non-null  bool
 30  IsAccurate          151985 non-null  bool
dtypes: bool(4), float64(9), int64(1), object(17)
memory usage: 31.9+ MB

In [24]:
laps_df.isnull().sum()

Time                       0
Driver                     0
DriverNumber               0
LapTime                 2592
LapNumber                  0
Stint                    354
PitOutTime            146837
PitInTime             146780
Sector1Time             3305
Sector2Time              319
Sector3Time              489
Sector1SessionTime      3686
Sector2SessionTime       319
Sector3SessionTime       489
SpeedI1                  243
SpeedI2                 1130
SpeedFL                 5445
SpeedST                  320
IsPersonalBest           184
Compound                 780
TyreLife                1058
FreshTyre                  0
Team                       0
LapStartTime               0
LapStartDate               0
TrackStatus               23
Position                 241
Deleted                    0
DeletedReason         150169
FastF1Generated            0
IsAccurate                 0
dtype: int64

In [25]:
laps_df.duplicated().sum()

np.int64(9527)

In [26]:
laps_df[laps_df.duplicated(keep=False)].head(20)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
2069,0 days 00:34:06.302000,GAS,10,0 days 00:01:19.106000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:33.352000,...,True,AlphaTauri,0 days 00:32:47.006000,2020-07-05 13:12:47.229,1.0,12.0,False,NaN,False,False
2070,0 days 00:35:18.714000,GAS,10,0 days 00:01:12.412000,2.0,1.0,NaN,NaN,0 days 00:00:17.960000,0 days 00:00:32.228000,...,True,AlphaTauri,0 days 00:34:06.302000,2020-07-05 13:14:06.525,1.0,12.0,False,NaN,False,True
2071,0 days 00:36:30.025000,GAS,10,0 days 00:01:11.311000,3.0,1.0,NaN,NaN,0 days 00:00:17.513000,0 days 00:00:31.717000,...,True,AlphaTauri,0 days 00:35:18.714000,2020-07-05 13:15:18.937,1.0,12.0,False,NaN,False,True
2072,0 days 00:37:40.750000,GAS,10,0 days 00:01:10.725000,4.0,1.0,NaN,NaN,0 days 00:00:17.410000,0 days 00:00:31.510000,...,True,AlphaTauri,0 days 00:36:30.025000,2020-07-05 13:16:30.248,1.0,12.0,False,NaN,False,True
2073,0 days 00:38:52.261000,GAS,10,0 days 00:01:11.511000,5.0,1.0,NaN,NaN,0 days 00:00:17.464000,0 days 00:00:31.827000,...,True,AlphaTauri,0 days 00:37:40.750000,2020-07-05 13:17:40.973,1.0,12.0,False,NaN,False,True
2074,0 days 00:40:04.289000,GAS,10,0 days 00:01:12.028000,6.0,1.0,NaN,NaN,0 days 00:00:17.944000,0 days 00:00:31.741000,...,True,AlphaTauri,0 days 00:38:52.261000,2020-07-05 13:18:52.484,1.0,12.0,False,NaN,False,True
2075,0 days 00:41:15.462000,GAS,10,0 days 00:01:11.173000,7.0,1.0,NaN,NaN,0 days 00:00:17.898000,0 days 00:00:31.660000,...,True,AlphaTauri,0 days 00:40:04.289000,2020-07-05 13:20:04.512,1.0,12.0,False,NaN,False,True
2076,0 days 00:42:26.374000,GAS,10,0 days 00:01:10.912000,8.0,1.0,NaN,NaN,0 days 00:00:17.846000,0 days 00:00:31.491000,...,True,AlphaTauri,0 days 00:41:15.462000,2020-07-05 13:21:15.685,1.0,12.0,False,NaN,False,True
2077,0 days 00:43:37.201000,GAS,10,0 days 00:01:10.827000,9.0,1.0,NaN,NaN,0 days 00:00:17.883000,0 days 00:00:31.301000,...,True,AlphaTauri,0 days 00:42:26.374000,2020-07-05 13:22:26.597,1.0,12.0,False,NaN,False,False
2078,0 days 00:44:48.171000,GAS,10,0 days 00:01:10.970000,10.0,1.0,NaN,NaN,0 days 00:00:17.883000,0 days 00:00:31.593000,...,True,AlphaTauri,0 days 00:43:37.201000,2020-07-05 13:23:37.424,1.0,11.0,False,NaN,False,True
2079,0 days 00:45:59.124000,GAS,10,0 days 00:01:10.953000,11.0,1.0,NaN,NaN,0 days 00:00:17.957000,0 days 00:00:31.554000,...,True,AlphaTauri,0 days 00:44:48.171000,2020-07-05 13:24:48.394,1.0,11.0,False,NaN,False,True
2080,0 days 00:47:09.886000,GAS,10,0 days 00:01:10.762000,12.0,1.0,NaN,NaN,0 days 00:00:17.866000,0 days 00:00:31.417000,...,True,AlphaTauri,0 days 00:45:59.124000,2020-07-05 13:25:59.347,1.0,10.0,False,NaN,False,True
2081,0 days 00:48:20.730000,GAS,10,0 days 00:01:10.844000,13.0,1.0,NaN,NaN,0 days 00:00:17.883000,0 days 00:00:31.518000,...,True,AlphaTauri,0 days 00:47:09.886000,2020-07-05 13:27:10.109,1.0,10.0,False,NaN,False,True
2082,0 days 00:49:31.442000,GAS,10,0 days 00:01:10.712000,14.0,1.0,NaN,NaN,0 days 00:00:17.885000,0 days 00:00:31.362000,...,True,AlphaTauri,0 days 00:48:20.730000,2020-07-05 13:28:20.953,1.0,9.0,False,NaN,False,True
2083,0 days 00:50:42.381000,GAS,10,0 days 00:01:10.939000,15.0,1.0,NaN,NaN,0 days 00:00:17.910000,0 days 00:00:31.493000,...,True,AlphaTauri,0 days 00:49:31.442000,2020-07-05 13:29:31.665,1.0,9.0,False,NaN,False,True
2084,0 days 00:51:53.114000,GAS,10,0 days 00:01:10.733000,16.0,1.0,NaN,NaN,0 days 00:00:17.823000,0 days 00:00:31.456000,...,True,AlphaTauri,0 days 00:50:42.381000,2020-07-05 13:30:42.604,1.0,9.0,False,NaN,False,True
2085,0 days 00:53:03.649000,GAS,10,0 days 00:01:10.535000,17.0,1.0,NaN,NaN,0 days 00:00:17.809000,0 days 00:00:31.317000,...,True,AlphaTauri,0 days 00:51:53.114000,2020-07-05 13:31:53.337,1.0,9.0,False,NaN,False,True
2086,0 days 00:54:14.321000,GAS,10,0 days 00:01:10.672000,18.0,1.0,NaN,NaN,0 days 00:00:17.811000,0 days 00:00:31.353000,...,True,AlphaTauri,0 days 00:53:03.649000,2020-07-05 13:33:03.872,1.0,9.0,False,NaN,False,True
2087,0 days 00:55:24.889000,GAS,10,0 days 00:01:10.568000,19.0,1.0,NaN,NaN,0 days 00:00:17.855000,0 days 00:00:31.341000,...,True,AlphaTauri,0 days 00:54:14.321000,2020-07-05 13:34:14.544,1.0,9.0,False,NaN,False,True
2088,0 days 00:56:35.499000,GAS,10,0 days 00:01:10.610000,20.0,1.0,NaN,NaN,0 days 00:00:17.818000,0 days 00:00:31.333000,...,True,AlphaTauri,0 days 00:55:24.889000,2020-07-05 13:35:25.112,12.0,9.0,False,NaN,False,True

In [27]:
laps_df[laps_df.duplicated()].head(10)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
11505,0 days 00:34:06.302000,GAS,10,0 days 00:01:19.106000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:33.352000,...,True,AlphaTauri,0 days 00:32:47.006000,2020-07-05 13:12:47.229,1.0,12.0,False,NaN,False,False
11506,0 days 00:35:18.714000,GAS,10,0 days 00:01:12.412000,2.0,1.0,NaN,NaN,0 days 00:00:17.960000,0 days 00:00:32.228000,...,True,AlphaTauri,0 days 00:34:06.302000,2020-07-05 13:14:06.525,1.0,12.0,False,NaN,False,True
11507,0 days 00:36:30.025000,GAS,10,0 days 00:01:11.311000,3.0,1.0,NaN,NaN,0 days 00:00:17.513000,0 days 00:00:31.717000,...,True,AlphaTauri,0 days 00:35:18.714000,2020-07-05 13:15:18.937,1.0,12.0,False,NaN,False,True
11508,0 days 00:37:40.750000,GAS,10,0 days 00:01:10.725000,4.0,1.0,NaN,NaN,0 days 00:00:17.410000,0 days 00:00:31.510000,...,True,AlphaTauri,0 days 00:36:30.025000,2020-07-05 13:16:30.248,1.0,12.0,False,NaN,False,True
11509,0 days 00:38:52.261000,GAS,10,0 days 00:01:11.511000,5.0,1.0,NaN,NaN,0 days 00:00:17.464000,0 days 00:00:31.827000,...,True,AlphaTauri,0 days 00:37:40.750000,2020-07-05 13:17:40.973,1.0,12.0,False,NaN,False,True
11510,0 days 00:40:04.289000,GAS,10,0 days 00:01:12.028000,6.0,1.0,NaN,NaN,0 days 00:00:17.944000,0 days 00:00:31.741000,...,True,AlphaTauri,0 days 00:38:52.261000,2020-07-05 13:18:52.484,1.0,12.0,False,NaN,False,True
11511,0 days 00:41:15.462000,GAS,10,0 days 00:01:11.173000,7.0,1.0,NaN,NaN,0 days 00:00:17.898000,0 days 00:00:31.660000,...,True,AlphaTauri,0 days 00:40:04.289000,2020-07-05 13:20:04.512,1.0,12.0,False,NaN,False,True
11512,0 days 00:42:26.374000,GAS,10,0 days 00:01:10.912000,8.0,1.0,NaN,NaN,0 days 00:00:17.846000,0 days 00:00:31.491000,...,True,AlphaTauri,0 days 00:41:15.462000,2020-07-05 13:21:15.685,1.0,12.0,False,NaN,False,True
11513,0 days 00:43:37.201000,GAS,10,0 days 00:01:10.827000,9.0,1.0,NaN,NaN,0 days 00:00:17.883000,0 days 00:00:31.301000,...,True,AlphaTauri,0 days 00:42:26.374000,2020-07-05 13:22:26.597,1.0,12.0,False,NaN,False,False
11514,0 days 00:44:48.171000,GAS,10,0 days 00:01:10.970000,10.0,1.0,NaN,NaN,0 days 00:00:17.883000,0 days 00:00:31.593000,...,True,AlphaTauri,0 days 00:43:37.201000,2020-07-05 13:23:37.424,1.0,11.0,False,NaN,False,True

In [28]:
laps_df.columns.tolist()

['Time',
 'Driver',
 'DriverNumber',
 'LapTime',
 'LapNumber',
 'Stint',
 'PitOutTime',
 'PitInTime',
 'Sector1Time',
 'Sector2Time',
 'Sector3Time',
 'Sector1SessionTime',
 'Sector2SessionTime',
 'Sector3SessionTime',
 'SpeedI1',
 'SpeedI2',
 'SpeedFL',
 'SpeedST',
 'IsPersonalBest',
 'Compound',
 'TyreLife',
 'FreshTyre',
 'Team',
 'LapStartTime',
 'LapStartDate',
 'TrackStatus',
 'Position',
 'Deleted',
 'DeletedReason',
 'FastF1Generated',
 'IsAccurate']

In [29]:
print(laps_df.columns.tolist())

['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime', 'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest', 'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime', 'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason', 'FastF1Generated', 'IsAccurate']

In [30]:
laps_df[laps_df.duplicated(keep=False)].head(10)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
2069,0 days 00:34:06.302000,GAS,10,0 days 00:01:19.106000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:33.352000,...,True,AlphaTauri,0 days 00:32:47.006000,2020-07-05 13:12:47.229,1.0,12.0,False,NaN,False,False
2070,0 days 00:35:18.714000,GAS,10,0 days 00:01:12.412000,2.0,1.0,NaN,NaN,0 days 00:00:17.960000,0 days 00:00:32.228000,...,True,AlphaTauri,0 days 00:34:06.302000,2020-07-05 13:14:06.525,1.0,12.0,False,NaN,False,True
2071,0 days 00:36:30.025000,GAS,10,0 days 00:01:11.311000,3.0,1.0,NaN,NaN,0 days 00:00:17.513000,0 days 00:00:31.717000,...,True,AlphaTauri,0 days 00:35:18.714000,2020-07-05 13:15:18.937,1.0,12.0,False,NaN,False,True
2072,0 days 00:37:40.750000,GAS,10,0 days 00:01:10.725000,4.0,1.0,NaN,NaN,0 days 00:00:17.410000,0 days 00:00:31.510000,...,True,AlphaTauri,0 days 00:36:30.025000,2020-07-05 13:16:30.248,1.0,12.0,False,NaN,False,True
2073,0 days 00:38:52.261000,GAS,10,0 days 00:01:11.511000,5.0,1.0,NaN,NaN,0 days 00:00:17.464000,0 days 00:00:31.827000,...,True,AlphaTauri,0 days 00:37:40.750000,2020-07-05 13:17:40.973,1.0,12.0,False,NaN,False,True
2074,0 days 00:40:04.289000,GAS,10,0 days 00:01:12.028000,6.0,1.0,NaN,NaN,0 days 00:00:17.944000,0 days 00:00:31.741000,...,True,AlphaTauri,0 days 00:38:52.261000,2020-07-05 13:18:52.484,1.0,12.0,False,NaN,False,True
2075,0 days 00:41:15.462000,GAS,10,0 days 00:01:11.173000,7.0,1.0,NaN,NaN,0 days 00:00:17.898000,0 days 00:00:31.660000,...,True,AlphaTauri,0 days 00:40:04.289000,2020-07-05 13:20:04.512,1.0,12.0,False,NaN,False,True
2076,0 days 00:42:26.374000,GAS,10,0 days 00:01:10.912000,8.0,1.0,NaN,NaN,0 days 00:00:17.846000,0 days 00:00:31.491000,...,True,AlphaTauri,0 days 00:41:15.462000,2020-07-05 13:21:15.685,1.0,12.0,False,NaN,False,True
2077,0 days 00:43:37.201000,GAS,10,0 days 00:01:10.827000,9.0,1.0,NaN,NaN,0 days 00:00:17.883000,0 days 00:00:31.301000,...,True,AlphaTauri,0 days 00:42:26.374000,2020-07-05 13:22:26.597,1.0,12.0,False,NaN,False,False
2078,0 days 00:44:48.171000,GAS,10,0 days 00:01:10.970000,10.0,1.0,NaN,NaN,0 days 00:00:17.883000,0 days 00:00:31.593000,...,True,AlphaTauri,0 days 00:43:37.201000,2020-07-05 13:23:37.424,1.0,11.0,False,NaN,False,True

In [31]:
laps_df[laps_df.duplicated()].head(10)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
11505,0 days 00:34:06.302000,GAS,10,0 days 00:01:19.106000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:33.352000,...,True,AlphaTauri,0 days 00:32:47.006000,2020-07-05 13:12:47.229,1.0,12.0,False,NaN,False,False
11506,0 days 00:35:18.714000,GAS,10,0 days 00:01:12.412000,2.0,1.0,NaN,NaN,0 days 00:00:17.960000,0 days 00:00:32.228000,...,True,AlphaTauri,0 days 00:34:06.302000,2020-07-05 13:14:06.525,1.0,12.0,False,NaN,False,True
11507,0 days 00:36:30.025000,GAS,10,0 days 00:01:11.311000,3.0,1.0,NaN,NaN,0 days 00:00:17.513000,0 days 00:00:31.717000,...,True,AlphaTauri,0 days 00:35:18.714000,2020-07-05 13:15:18.937,1.0,12.0,False,NaN,False,True
11508,0 days 00:37:40.750000,GAS,10,0 days 00:01:10.725000,4.0,1.0,NaN,NaN,0 days 00:00:17.410000,0 days 00:00:31.510000,...,True,AlphaTauri,0 days 00:36:30.025000,2020-07-05 13:16:30.248,1.0,12.0,False,NaN,False,True
11509,0 days 00:38:52.261000,GAS,10,0 days 00:01:11.511000,5.0,1.0,NaN,NaN,0 days 00:00:17.464000,0 days 00:00:31.827000,...,True,AlphaTauri,0 days 00:37:40.750000,2020-07-05 13:17:40.973,1.0,12.0,False,NaN,False,True
11510,0 days 00:40:04.289000,GAS,10,0 days 00:01:12.028000,6.0,1.0,NaN,NaN,0 days 00:00:17.944000,0 days 00:00:31.741000,...,True,AlphaTauri,0 days 00:38:52.261000,2020-07-05 13:18:52.484,1.0,12.0,False,NaN,False,True
11511,0 days 00:41:15.462000,GAS,10,0 days 00:01:11.173000,7.0,1.0,NaN,NaN,0 days 00:00:17.898000,0 days 00:00:31.660000,...,True,AlphaTauri,0 days 00:40:04.289000,2020-07-05 13:20:04.512,1.0,12.0,False,NaN,False,True
11512,0 days 00:42:26.374000,GAS,10,0 days 00:01:10.912000,8.0,1.0,NaN,NaN,0 days 00:00:17.846000,0 days 00:00:31.491000,...,True,AlphaTauri,0 days 00:41:15.462000,2020-07-05 13:21:15.685,1.0,12.0,False,NaN,False,True
11513,0 days 00:43:37.201000,GAS,10,0 days 00:01:10.827000,9.0,1.0,NaN,NaN,0 days 00:00:17.883000,0 days 00:00:31.301000,...,True,AlphaTauri,0 days 00:42:26.374000,2020-07-05 13:22:26.597,1.0,12.0,False,NaN,False,False
11514,0 days 00:44:48.171000,GAS,10,0 days 00:01:10.970000,10.0,1.0,NaN,NaN,0 days 00:00:17.883000,0 days 00:00:31.593000,...,True,AlphaTauri,0 days 00:43:37.201000,2020-07-05 13:23:37.424,1.0,11.0,False,NaN,False,True

In [32]:
laps_df.columns.tolist()

['Time',
 'Driver',
 'DriverNumber',
 'LapTime',
 'LapNumber',
 'Stint',
 'PitOutTime',
 'PitInTime',
 'Sector1Time',
 'Sector2Time',
 'Sector3Time',
 'Sector1SessionTime',
 'Sector2SessionTime',
 'Sector3SessionTime',
 'SpeedI1',
 'SpeedI2',
 'SpeedFL',
 'SpeedST',
 'IsPersonalBest',
 'Compound',
 'TyreLife',
 'FreshTyre',
 'Team',
 'LapStartTime',
 'LapStartDate',
 'TrackStatus',
 'Position',
 'Deleted',
 'DeletedReason',
 'FastF1Generated',
 'IsAccurate']